generated: '2026-07-11'
method: probed
source: live DNS/TLS/HTTP probes of apis.yml + OpenAPI hosts
hosts:
- host: www.wunderground.com
  https: true
  tls_version: TLSv1.3
  cert_expires: Jan  5 23:59:59 2027 GMT
  hsts: false
- host: api.weather.com
  https: true
  tls_version: TLSv1.3
  cert_expires: Jan  6 23:59:59 2027 GMT
  hsts: null
domains:
- domain: wunderground.com
  dnssec: false
  caa:
  - 0 issue "letsencrypt.org"
  - 0 issue "amazon.com"
  - 0 issue "sectigo.com"
  - 0 issue "digicert.com"
  spf: true
  dmarc: false
- domain: weather.com
  dnssec: false
  caa:
  - 10 issue "digicert.com"
  - 0 issue "sectigo.com"
  - 100 issue "letsencrypt.org"
  - 0 issue "globalsign.com"
  - 0 issue "amazon.com"
  - 0 issue "pki.goog"
  spf: true
  dmarc: true
  dmarc_policy: quarantine
